export const ADD_POST = 'POST_ACTION:ADD_POST';
export const SET_ALL_POSTS = 'POST_ACTION:SET_ALL_POSTS';
export const TOGGLE_LIKE = 'POST_ACTION:TOGGLE_LIKE';
export const TOGGLE_EXPANDED_POST_VISIBILITY = 'POST_ACTION:TOGGLE_EXPANDED_POST_VISIBILITY';
export const ADD_COMMENT = 'POST_ACTION:ADD_COMMENT';
export const SET_SHARED_POST_INFO = 'POST_ACTION:SET_SHARED_POST_INFO';
