env:
  browser: true

settings:
  react:
    version: 'detect'

parserOptions:
  project:
    - ./jsconfig.json

extends:
  - ../.eslintrc.yml
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/typescript

rules:
  react/jsx-no-bind:
    - error
    - ignoreRefs: true
  react/jsx-curly-brace-presence:
    - error
    - never
  react/self-closing-comp:
    - error
  react/jsx-boolean-value:
    - error
  import/no-unresolved:
    - off

overrides:
  - files:
      - vite.config.js
    rules:
      import/no-default-export:
        - off
