extends:
  - ../.stylelintrc.yml
  - stylelint-config-standard-scss

plugins:
  - stylelint-scss

rules:
  selector-class-pattern: null
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
