env:
  node: true

parserOptions:
  project:
    - ./tsconfig.json

extends:
  - ../.eslintrc.yml

overrides:
  - files:
      - knexfile.js
    rules:
      'import/no-default-export':
        - off
  - files:
      - src/db/migrations/**/*.js
    rules:
      'unicorn/filename-case':
        - error
        - case: snakeCase
